Repository aws-samples/serverless-patterns, pull requests merged in 2024-02, with the labels that each got.

#2073 Update template.yaml. Fix mapping typo
  apigw-route53-failover/template.yaml
Labels: Patterns Guardian approved

#2058 New Serverless Pattern - SQS to SQS message copy with filter using EventBridge Pipe using SAM
  sqs-eventbridgepipes-sqs-msg-copy-data-filter-sam/README.md
  sqs-eventbridgepipes-sqs-msg-copy-data-filter-sam/example-pattern.json
  sqs-eventbridgepipes-sqs-msg-copy-data-filter-sam/image/architecture.png
  sqs-eventbridgepipes-sqs-msg-copy-data-filter-sam/receive-messages-from-target-queue.sh
  sqs-eventbridgepipes-sqs-msg-copy-data-filter-sam/send-messages-to-source-queue.sh
  sqs-eventbridgepipes-sqs-msg-copy-data-filter-sam/sqs-to-sqs-message-copy-with-eventbridgepipes.json
  sqs-eventbridgepipes-sqs-msg-copy-data-filter-sam/template.yaml
Labels: valid-example-pattern-file, Patterns Guardian approved

#2081 Modified the aws sqs send-message command to properly close the value…
  eventbridge-pipes-sqs-to-stepfunctions-cdk-python/README.md
Labels: missing-example-pattern-file, Patterns Guardian approved

#2117 Add metric tags to templates
  alb-cognito-lambda/template.yaml
  alb-lambda-rest-api-sam-py/template.yaml
  alb-lambda-rust/template.yml
  amplify_cognito_apigateway_lambda_envvariables/template.yaml
  apigw-api-key/template.yaml
  apigw-caching-sam/template.yaml
  apigw-client-certificate/template.yaml
  apigw-cloudwatch/template.yaml
  apigw-comprehend/template.yaml
  apigw-cors-nonproxy/template.yaml
Labels: Patterns Guardian approved

#2085 Added api-lambda-ses
  api-lambda-ses/Readme.md
  api-lambda-ses/api-lambda-ses-sam-python.json
  api-lambda-ses/example-pattern.json
  api-lambda-ses/src/api.yml
  api-lambda-ses/src/index.py
  api-lambda-ses/src/index.zip
  api-lambda-ses/template.yml
Labels: valid-example-pattern-file, Patterns Guardian approved

#2053 Wildcard pattern match in Amazon EventBridge rule (S3-EventBridge-SQS)
  s3-eventbridge-wildcard-sam/README.md
  s3-eventbridge-wildcard-sam/abc-data.csv
  s3-eventbridge-wildcard-sam/empty-s3-bucket.sh
  s3-eventbridge-wildcard-sam/example-pattern.json
  s3-eventbridge-wildcard-sam/image/architecture.png
  s3-eventbridge-wildcard-sam/s3-eventbridge-wildcard-sam.json
  s3-eventbridge-wildcard-sam/template.yaml
  s3-eventbridge-wildcard-sam/upload-to-s3.sh
  s3-eventbridge-wildcard-sam/xyz-data.csv
Labels: valid-example-pattern-file, Patterns Guardian approved

#2046 New serverless pattern - Eventbridge bus to Appsync Subscription
  eventbridge-appsync-subscription-sam/README.md
  eventbridge-appsync-subscription-sam/eventbridge-appsync-subscription-sam.json
  eventbridge-appsync-subscription-sam/example-pattern.json
  eventbridge-appsync-subscription-sam/images/appsync-1.png
  eventbridge-appsync-subscription-sam/images/appsync-2.png
  eventbridge-appsync-subscription-sam/images/eventbridge-1.png
  eventbridge-appsync-subscription-sam/images/eventbridge-2.png
  eventbridge-appsync-subscription-sam/images/eventbridge-3.png
  eventbridge-appsync-subscription-sam/schema.graphql
  eventbridge-appsync-subscription-sam/template.yaml
Labels: valid-example-pattern-file, Patterns Guardian approved

#2040 lambda-aurora-serverless: include project JSON and README changes
  lambda-aurora-serverless/README.md
  lambda-aurora-serverless/example-pattern.json
  lambda-aurora-serverless/lambda-aurora.json
Labels: valid-example-pattern-file, Patterns Guardian approved

#2106 New Serverless Pattern - Receive Email using Amazon SES
  ses-lambda-sam/README.md
  ses-lambda-sam/example-pattern.json
  ses-lambda-sam/images/architecture.png
  ses-lambda-sam/ses-lambda-sam.json
  ses-lambda-sam/src/process-email.py
  ses-lambda-sam/template.yaml
Labels: Patterns Guardian approved

#2077 adding the json file for PR#2041
  sam-dynamodb-glue-transform/sam-dynamodb-glue-transform.json
Labels: Patterns Guardian approved

#2060 New Serverless Patter - FIFO SQS Redrive
  fifo-sqs-redrive/README.md
  fifo-sqs-redrive/example-pattern.json
  fifo-sqs-redrive/fifo-sqs-redrive.json
  fifo-sqs-redrive/fifo-sqs-redrive/fifo-sqs-redrive.json
  fifo-sqs-redrive/image/all-msg-processed.png
  fifo-sqs-redrive/image/architecture.png
  fifo-sqs-redrive/image/lambda-processing-error.png
  fifo-sqs-redrive/image/lambda-reprocessed-msg.png
  fifo-sqs-redrive/image/msg-in-dlq.png
  fifo-sqs-redrive/originalmessage/app.py
  fifo-sqs-redrive/redrivenmessage/app.py
  fifo-sqs-redrive/template.yaml
Labels: valid-example-pattern-file, Patterns Guardian approved

#2139 Add metric tags
  apigw-sqs-rest/template.yaml
  apigw-throttle-sam/template.yaml
  apigw-usage-plans/template.yaml
  apigw-vpclink-pvt-alb/template.yml
  apigw-waf-sam/template.yaml
  apigw-websocket-api-bedrock-streaming/template.yaml
  apigw-websocket-api-connection-dynamodb/template.yaml
  apigw-websocket-api-lambda-authorizer/template.yaml
  apigw-websocket-api-lambda/template.yml
  apigw-websocket-api-sfn-async/template.yaml
  apigw-websocket-api-sfn-sync/template.yaml
  apigw-websocket-api-sns/template.yaml
  apigw-websocket-api-sqs-lambda-java/template.yaml
  apigw-websocket-api-sqs-lambda/template.yaml
  appconfig-feature-flag-sam/template.yaml
  appconfig-lambda-rust/template.yml
  appsync-apigateway-dynamodb-sam/template.yaml
  appsync-bedrock/template.yaml
  appsync-dynamodb-singletable-js-resolver/template.yaml
  appsync-dynamodb-singletable/template.yaml
  appsync-dynamodb/template.yaml
  appsync-lambda-kendra/template.yaml
  appsync-lambda-sfn-sam/template.yaml
  appsync-stepfunctions-express-sam/template.yaml
  bedrock-lambda-nodejs/template.yml
  cdk-firehose-s3-transform-java/template.yml
  cdn-dash-sam/template.yaml
  cfn-custom-resource-s3-create/template.yml
  cloudfront-apigw-http-api-lambda-rust/template.yml
  cloudfront-apigw-rest-api-lambda-dynamodb-sam/template.yaml
  cloudfront-lambda-url-java/template.yml
  cloudfront-lambda-url-rust/template.yml
  cloudfront-s3-oac-sam/template.yaml
  cloudtrail-lambda-slack-sam/template.yml
  cloudwatch-logs-subscription-lambda-sam/template.yaml
  cloudwatch-rum-cognito/template.yaml
  codecommit-s3/template.yaml
  cognito-httpapi/template.yaml
  cognito-restapi-vpclink/template.yml
  cognito-restapi/template.yaml
  cognito-sns-sms-origination-id-sam/template.yaml
  cognito-user-pool/template.yaml
  cw-sns-secretsmanager/template.yaml
  dynamic-bedrock-svls-sam/template.yaml
  dynamodb-eventbridge-java/template.yaml
  dynamodb-eventbridge/template.yaml
  dynamodb-kinesis/template.yaml
  dynamodb-lambda/template.yaml
  dynamodb-streams-appsync-subscription/template.yaml
  dynamodb-streams-lambda-event-filters/template.yaml
Labels: Patterns Guardian approved

#2143 Add metric tags
  s3-sqs-lambda-sam-java/template.yml
  s3-sqs-lambda/template.yaml
  s3-sqs/template.yaml
  sam-webapp-cognito/template.yaml
  sfn-apigw/template.yaml
  sfn-comprehend-sam/template.yaml
  sfn-dynamodb/template.yaml
  sfn-ecs-sam/template.yml
  sfn-eventbridge/template.yaml
  sfn-lambda-dynamodb/template.yml
  sfn-lambda-function-crossaccount/template.yaml
  sfn-lambda-lambda/template.yaml
  sfn-lambda/template.yaml
  sfn-log-export/template.yaml
  sfn-s3/template.yaml
  sfn-sfn/template.yml
  sfn-sns/template.yml
  sfn-sqs/template.yaml
  sns-firehose-opensearch/template.yml
  sns-firehose/template.yaml
  sns-lambda-slack-integration-SAM/template.yaml
  sns-lambda/template.yaml
  sns-sqs-fanout/template.yaml
  sns-sqs-lambda-rust-sam/template.yml
  sns-sqs-lambda-xray/template.yaml
  sns-sqs/template.yaml
  sqs-eventbridgepipes-sqs-msg-copy-data-filter-sam/template.yaml
  sqs-lambda-ddb-sam-ts/template.yaml
  sqs-lambda-dynamodb-sam-java/template.yml
  sqs-lambda-partial-batch-rust-sam/template.yml
  sqs-lambda-rust-sam/template.yml
  sqs-lambda/template.yaml
  sqs-stepfunctions-pipes-pattern/template.yaml
  step-function-sync-rest-api/template.yml
  step-functions-athena-glue-sam/template.yml
  stepfunctions-bedrock-sam/template.yaml
  stepfunctions-eventbridge-lambda-sam-java/template.yml
  stepfunctions-eventbridge-schedule-sam-python/template.yaml
  stepfunctions-fargate-lambda/template.yaml
  stepfunctions-httpendpoint-sam/template.yaml
  systems-manager-automation-to-lambda/template.yaml
  systems-manager-automation-to-stepfunctions/template.yaml
  vpc-lattice-lambda/template.yaml
  waf-apigw-rest/template.yaml
Labels: Patterns Guardian approved

#2140 Add metrics tag
  dynamodb-streams-lambda-eventbridge-sam-node/template.yml
  dynamodb-streams-lambda-eventbridge-sam-rust/template.yml
  eventbridge-batch-sam/template.yaml
  eventbridge-cloudwatch/template.yaml
  eventbridge-kinesis/template.yaml
  eventbridge-lambda-fsx-openzfs-periodic-replication/template.yaml
  eventbridge-lambda-rust/template.yml
  eventbridge-lambda/template.yaml
  eventbridge-pipes-ddb-stream-lambda-sfn-enrich/template.yaml
  eventbridge-pipes-ddbstream-sfn/template.yaml
  eventbridge-pipes-ddbstream-to-eventbridge-suffix-matching/template.yaml
  eventbridge-pipes-ddbstream-to-eventbridge/template.yaml
  eventbridge-pipes-ddbstream-with-filters-to-eventbridge/template.yaml
  eventbridge-pipes-dynamodbstream-sns/template.yaml
  eventbridge-pipes-kinesis-to-kinesis-with-filtering/template.yaml
  eventbridge-pipes-msk-iam-auth-to-lambda/template.yaml
  eventbridge-pipes-msk-to-lambda/template.yaml
  eventbridge-pipes-sqs-enrich-with-api-destination/template.yaml
  eventbridge-pipes-sqs-enrich-with-sfdc/template.yaml
  eventbridge-pipes-sqs-lambda-api-destination/template.yaml
  eventbridge-pipes-sqs-to-aws-batch-with-filters/template.yaml
  eventbridge-pipes-sqs-to-eventbridge-with-filters/template.yaml
  eventbridge-pipes-sqs-to-lambda-with-stepfunction-enrichment/template.yaml
  eventbridge-pipes-sqs-to-stepfunctions/template.yaml
  eventbridge-rule-to-ssm-automation-sam/template.yaml
  eventbridge-schedule-remove-one-time-schedules/template.yaml
  eventbridge-schedule-stepfunctions-sam/template.yaml
  eventbridge-schedule-to-lambda-sam-go/template.yaml
  eventbridge-schedule-to-lambda-sam-java/template.yaml
  eventbridge-schedule-to-lambda/template.yaml
  eventbridge-schedule-to-sqs-sam/template.yaml
  eventbridge-schedule-to-ssm-sam/template.yaml
  eventbridge-scheduled-batch-sam/template.yaml
  eventbridge-scheduled-lambda-java/template.yaml
  eventbridge-scheduled-lambda/template.yaml
  eventbridge-sfn-redrive/template.yaml
  eventbridge-sfn/template.yaml
  eventbridge-sns-lambda/template.yaml
  eventbridge-sns/template.yaml
  eventbridge-sqs/template.yaml
  eventbridge-to-appsync-sam/template.yaml
  firehose-transformation-sam-go/template.yml
  firehose-transformation-sam-java/template.yaml
  firehose-transformation-sam-python/template.yaml
  firehose-transformation-sam/template.yaml
  inspector-eventbridge-multi-destinations/template.yaml
  iot-dynamodb/template.yaml
  iot-lambda/template.yaml
  iot-mqttoverhttp-customauth/template.yaml
  iot-s3/template.yaml
  iot-sns-sqs-sam/template.yaml
  kds-kdf-opensearch/template.yaml
  kinesis-data-stream-firehose-apigw-sam/template.yaml
  kinesis-data-stream-firehose-s3-sam-java/template.yml
  kinesis-lambda-efo/template.yaml
  kinesis-lambda-error-handling/template.yaml
  kinesis-lambda/template.yaml
  lambda-athena-sam/template.yaml
  lambda/template.yaml
Labels: Patterns Guardian approved
